### ISSUE TITLE
.travis.yml file will not allow a pull request to be made

### ISSUE THREAD

**Issue by liameirose** [Duke-BME-Design/unit-testing-liameirose#1]
Hi Dr. Palmeri,

Sorry I was backpacking this weekend and just saw your message. I still cannot manage to merge my branch tachtest1. It seems to be a problem with the .travis.yml file. Since it doesn't allow me to create a pull request, I am not sure if you have access to my file either?

Lia

**Comment by mlp6** [comment]
@liameirose It looks like it worked for me w/o any changes: https://travis-ci.com/Duke-BME-Design/unit-testing-liameirose/builds/86408973

What am I missing?  There did not appear to be any open Pull Requests in this repo before the testing one that I'm created, so I'm not sure how you generated that run that you showed the log message from.

**Comment by liameirose** [comment]
@mlp6 Thank you for checking!

I generated it on the Travis CI website. I was confused when I couldn't generate a pull request? I am probably messing up the pull request? I am using git push, but it doesn't allow me to do anything after that once I am on GitHub?

**Comment by mlp6** [comment]
It looks like your branch was created out-of-sync from the associated `master` (I'm not sure how/why that would be).  My branch that I tested off of was a branch of your branch.  Are you seeing a message on GitHub that your histories are not compatible when you go to create the Pull Request?

**Comment by liameirose** [comment]
Yes! It says "there is nothing to compare with the two branches". This is really weird because I just used the git checkout -b. Do you have any suggestions of how to get them back "in sync"?

**Comment by mlp6** [comment]
You'll want to fix this locally (not on GitHub).  You can do so by checking into `master`, and then issuing a command like: `git merge --no-ff tachtest1 --allow-unrelated-histories`.  This will, of course, not run Travis CI, etc., but it will get your `master` happy with your changes.  You will hopefully be able to push that forward to git, branch from there, and all will play nicely.  I'm not sure how you got those diverted histories though...

**Comment by liameirose** [comment]
I created the README file directly from GitHub after creating the new branch...maybe that was my issue. Also I tried to checkout the master and it gave me this error?
 
(.venv) Lias-MacBook-Pro:unit-testing-liameirose liameirose$ git checkout master
error: pathspec 'master' did not match any file(s) known to git.

Sorry for my many issues, but I really appreciate your help!
